Repository ilo80/esiee-plus-bot, pull requests merged in 2025-01, with the labels that each got.

#10 [FEAT]: Add "statut_salle" command
  src/bot.ts
  src/commands/recherche_salles.ts
  src/commands/statut_salle.ts
  src/utils/ade.ts
  src/utils/date.ts
  src/utils/time.ts
Labels: enhancement

#12 [FIX] Change startHour comparison
  src/commands/recherche_salles.ts
Labels: bug

#13 [FIX/FEAT]: Fix room wrong info in "statut_salle" command
  src/commands/statut_salle.ts
  src/utils/ade.ts
Labels: bug, enhancement

#14 Fix timezone issue
  .env.example
  Dockerfile
  docker-compose.yaml
Labels: bug

#15 Fix typo recherche_salles.ts
  src/commands/recherche_salles.ts
Labels: bug

#16 [UPDATE] Update ade-planning-api to v1.0.4
  package-lock.json
  package.json
  src/utils/ade.ts
Labels: enhancement
